version: "3.7"

services:
    runner:
      image: tcardonne/github-runner:latest
      environment:
        RUNNER_NAME: "my-runner"
        RUNNER_REPOSITORY_URL: "https://github.com/AniAnu/GithubActions"
        RUNNER_LABELS: "test-label1"
        RUNNER_TOKEN: "AGGXR2GS2U423SZRUZCZEMTAUPJWI"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
